//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppWithDatabaseTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AnimalShelterEntities : DbContext
    {
        public AnimalShelterEntities()
            : base("name=AnimalShelterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aac_shelter_outcomes> aac_shelter_outcomes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spGetAnimals_Result> spGetAnimals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAnimals_Result>("spGetAnimals");
        }
    
        public virtual ObjectResult<spGetAnimals1_Result> spGetAnimals1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAnimals1_Result>("spGetAnimals1");
        }
    
        public virtual ObjectResult<spGetWaterRescue_Result> spGetWaterRescue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetWaterRescue_Result>("spGetWaterRescue");
        }
    
        public virtual ObjectResult<spGetDisasterIndividualRescue_Result> spGetDisasterIndividualRescue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDisasterIndividualRescue_Result>("spGetDisasterIndividualRescue");
        }
    
        public virtual ObjectResult<spGetMountainWildernessRescue_Result> spGetMountainWildernessRescue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMountainWildernessRescue_Result>("spGetMountainWildernessRescue");
        }
    
        public virtual ObjectResult<string> sp_CheckPassword(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CheckPassword", param1Parameter);
        }
    }
}
